import type { Metadata } from "next";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"; // Importation du Header
import Footer from "@/components/footer"; // Importation du Footer
<<<<<<< HEAD
import ToastProvider from "@/components/ToastProvider"; // Importation du ToastProvider
=======
import IA_bouton from "@/components/UI/IA_bouton";

>>>>>>> frontend-develop

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-1 mt-16">
          {children}
        </main>
<<<<<<< HEAD
        <ToastProvider /> {/* Ajout du ToastProvider ici */}
        <div className="w-full mt-20">
          <Footer />
=======
        <div className = "w-full mt-20">
          <IA_bouton/>
        <Footer/>
>>>>>>> frontend-develop
        </div>
      </body>
    </html>
  );
}
